name: build & push docker container
on:
  push:
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker meta
        id: metal
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metal.outputs.tags }}
          labels: ${{ steps.metal.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    deploy:
      runs-on: ubuntu-latest
      steps:          
        - name: Setup SSH Agent
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
        - name: Add server to known hosts
          run: |
            ssh-keyscan -H 54.254.253.188 >> ~/.ssh/known_hosts
            
        - name: Deploy ELK via Docker Compose
          run: |
            ssh github-action@54.254.253.188 << 'EOF'
              cd /data/elk
              docker-compose pull
              docker-compose up -d
            EOF